# dev-playbook.yml
- hosts: all  
  become: yes
  vars:
    ansible_user: root  
  tasks:  
    - name: Install npm  
      apt:  
        update_cache: yes  
        name: npm  
        state: present  

    - name: Install Node.js  
      apt:  
        name: nodejs  
        state: present