# dev-playbook.yml
- hosts: all
  become: yes
  tasks:
    - name: Install Node.js
      apt:
        update_cache: yes
        name: nodejs
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present
