# prod-playbook.yml
- hosts: all
  tasks:
    - name: Install Node.js
      apt:
        name: nodejs
        state: present

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install PM2
      npm:
        name: pm2
        global: yes
        state: present

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/default.conf
      notify:
        - restart nginx
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted